site_name: Mosiwi
theme:
  name: readthedocs
  highlightjs: true
  logo: web_logo/mosiwi_logo.png
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
